spring.application.name=wishmegift
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/blankmilitia-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE